### ISSUE TITLE
Autonomous Coding Agent

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/.github#105]
https://github.com/nus-apr/auto-code-rover

https://x.com/abhikroychoudh1/status/1777494000611852515

This might be worth setting up as an experiment first, and then a github action that responds to new issues being opened, with an event dispatcher so that we can run when specifications are modified and finalized. 

Finally we can make it a plugin for our kernel as part of a future task. 

I imagine it will do well with the simpler, and tighter scoped tasks!

**Comment by sergfeldman** [comment]
It would be great to conduct an experiment with these autonomous agents.

**Comment by chris-chris** [comment]
@pavlovcik 
I think this task is kind of R&D part.
If I integrate this module, the robot would be dumb at the first time. 
So, it would be better to clarify the expectation of the functionality.
 
For example, the robot can solve simple issue like minor bug.

**Comment by pavlovcik** [comment]
> @pavlovcik I think this task is kind of experimental feature. If I integrate this module, the robot would be dumb at the first time. So, it would be better to clarify the expectation of the functionality.
> 
> For example, the robot can solve simple issue like minor bug.

From what I understand, they already did all the hard work of making it smart. You just need to "connect the wires" basically set it up for use in our org/repos. Not sure the best way to implement, probably as CI in a single repo to start. Later should be integrated into our UbiquiBot so that it can run across all of our repos.

**Comment by chris-chris** [comment]
Got it. First, I'll try to connect the SWE-Agent as originally designed to address the issues in our GitHub repo.

**Comment by harjaapdhillon16** [comment]
@0x4007 Can you give me more details on this , like which tasks exactly should be included to use with the coding agent ? And once issues are fixed with the coding agent , should there be a pr raised for the changes made by the coding agent ?

**Comment by 0x4007** [comment]
I have sort of loose expectations for this. It's mostly a research project to set this up and get it working. In order for it to be indisputably set up correctly, perhaps we can run this as part of our CI on new issues created.

**Comment by harjaapdhillon16** [comment]
Meaning that the autonomous coding agent understands the issue filed , does the code changes that it understands and then make a pull request in the repo ? is that what we are looking to do ?(and set it up as a CI to auto capture and run whenever a new issue is created ?)

**Comment by 0x4007** [comment]
Yes it seems that the open source project did the heavy lifting, you just need to invoke it from a GitHub Action (with an issue created listener.) 

And possibly need to feed the relevant GitHub data in as a parameter of sorts.

Then ideally we should have a pull request output. We might even be able to break that apart into separate tasks, but the purpose of this task is to see if that tool actually works as advertised. Connecting all the wires end-to-end can potentially be handled iteratively if they are too large of projects.

**Comment by sergfeldman** [comment]
I would suggest to review 

GitHub Copilot Workspace
https://www.youtube.com/watch?v=L5Xny6yehUg 
https://github.blog/2024-04-29-github-copilot-workspace/

Tools similar to SWE agent
https://github.com/OpenDevin/OpenDevin OpenDevin
https://github.com/stitionai/devika Devika

**Comment by harjaapdhillon16** [comment]
@0x4007 these tools require docker build and deploy and then creating a conda env which is not possible to create inside github action environment https://github.com/harjaapdhillon16/code-rover

**Comment by 0x4007** [comment]
Anything is possible in a GitHub action environment. It's a Linux box. You can do it.

**Comment by harjaapdhillon16** [comment]
https://github.com/harjaapdhillon16/code-rover @0x4007 someone can continue on this , I developed it to the point where I have developed the docker image , but I have tried nearly everything I am not able to create an environment where I can execute this.

**Comment by 0x4007** [comment]
@gentlementlegen three messages is unnecessarily verbose

**Comment by gentlementlegen** [comment]
@0x4007 Only the first one is relevant and should have been displayed. I think this has been addressed in a PR within `command-start-stop`.

**Comment by 0x4007** [comment]
We can work with Cline instead. I also think this should be a plugin that can run when issues are filed.
