### ISSUE TITLE
DoraHacks Bounty Post

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity/.github#116]
https://dorahacks.io/daobounty
https://dorahacks.io/blog/guides/publish-a-bounty/

We are going to create a `daobounty` to post on `DoraHacks`. Essentially this will act as advertising space to a user base of 156K+ web3 centric users.

DoraHacks requires that you put up the bounty value via a transfer of the amount into an escrow pool. Since we handle payments we have a two options:

1. Ignore this completely and treat the value as an advertising fee for the space.
2. Create an actual reward pool and payout rules such as - $1,000 spread between 10 winners over the space of three months and anyone that successfully gets a PR merged in qualifies for an additional $100 on top of their task reward (handled manually).

I think two is the better option. It sticks to the rules of the platform and has legitimate payout and submission info. It further increases the incentive for newcomers and would be a healthy way to determine how successful this has been.

typically bounties are posted in a format such as:

#### Submission Rules

---

Gnosis is not a supported network although BNB, MATIC, and a few others are but this is trivial.

With any decent traction from this it makes the xp-system evermore relevant

**Comment by Keyrxng** [comment]
# UbiquityDAO Hackathon Bounty

This DoraHacks Bounty is brought to you by UbiquityDAO.

UbiquityDAO is an open-source platform that leverages DeFi and AI to optimize operations, ensuring accurate and fair compensation for contributions through comprehensive qualitative and quantitative evaluations. Our platform is fully open-source and continuously enhanced by the global developer community.

We have ready-to-start tasks available 24/7 on our platform, participants can collaborate asynchronously, leveraging our automated Permit2-based payment system to receive instant rewards upon task completion.

Join us in revolutionizing decentralized operations and explore the future of DAO work with UbiquityDAO.

## Links

- [ubq.fi](https://ubq.fi/) - An overview and introduction to UbiquityDAO
- [work.ubq.fi](https://work.ubq.fi/) - The UbiquityDAO work platform, find live tasks and bounties here
- [pay.ubq.fi](https://pay.ubq.fi/) - The UbiquityDAO payment platform, where you can claim your rewards
- [Developer introduction](https://dao.ubq.fi/ubiquityos-for-devs) - A guide to getting started with UbiquityOS DevPool

## Tracks

Our tasks cover many areas and below are some examples of the tracks you can participate in. Included are links to tasks which at the time of writing are currently available on the UbiquityDAO platform.

### Track 1: Solidity

Build and improve smart contracts that enhance the functionality and security of our platform. This track is ideal for developers proficient in Solidity and interested in contributing to the core infrastructure of decentralized applications.

- [Formal Verification](https://github.com/ubiquity/ubiquity-dollar/issues/926): Implement formal verification for Ubiquity Dollar smart contracts.
- [Security Monitoring](https://github.com/ubiquity/ubiquity-dollar/issues/927): Integrate security monitoring tools for Ubiquity Dollar smart contracts.
- [Invariant Testing](https://github.com/ubiquity/ubiquity-dollar/issues/563): Develop invariant tests using Foundry, Echidna, or other tools for Ubiquity Dollar smart contracts.

### Track 2: UbiquityOS

Contribute to the development of UbiquityOS by squashing bugs, building new plugins and features, and improving the overall user experience. This track is perfect for developers familiar with GitHub Automation, TypeScript, and Web3.

- [Telegram/GitHub Plugin](https://github.com/ubiquibot/plugins-wishlist/issues/25): Create a plugin which spawns a chatroom for each new task in UbiquityDAO.
- [Improve RPC Module Performance](https://github.com/ubiquity/rpc-handler/issues/30): Optimize the health check performed on endpoints in the RPC module.
- [Automatic Transfer Permits](https://github.com/ubiquibot/permit-generation/issues/6): Add a feature to the Permit2 module that automatically transfers the permit to the user.

### Track 3: AI

Create innovative AI solutions that integrate seamlessly with our platform. This includes developing predictive models, AI-driven analytics, and intelligent agents that can optimize various aspects of our operations.

- [Personal Agents](https://github.com/ubiquibot/plugins-wishlist/issues/3): Develop personal agents that automate actions for a user based on their preferences.
- [AI Specification Re-Writing](https://github.com/ubiquibot/plugins-wishlist/issues/2): Design a plugin which updates the specification of a task based on the issue comments.
- [Autonomous Coding Agent](https://github.com/ubiquity/.github/issues/105): Setup CI for the autonomous coding agents that can handle small tasks automatically.

## Bounty Reward Rules

1. **Eligibility**: Participation is open to individuals and teams worldwide.
2. **Submission**: A submission is any contribution that meets the task requirements and is merged within the bounty period.
3. **Evaluation**: Submissions will undergo our standard evaluation process, including code review, testing, and impact assessment.
4. **Compensation**: Rewards are distributed instantly upon task completion. As all tasks are already funded, you will earn the full reward amount for each completed task but will only be eligible for one DoraHacks bonus.

## Our Current Stats

- **Total Rewards**: $74,537 USD across 527 projects
- **Available Rewards**: $13,037 USD
- **Ongoing Rewards**: $3,950 USD
- **Completed Rewards**: $57,550 USD
- **Available Tasks**: 26
- **Ongoing Tasks**: 18
- **Completed Tasks**: 483

---

## About UbiquityDAO

### Revolutionizing Decentralized Operations

We synergize DeFi and AI to optimize operations, ensuring accurate and fair compensation through comprehensive qualitative and quantitative evaluations.

### Instant Dynamic Compensation

Quantified contributions are rewarded instantly upon task completion, boosting productivity and fairness in real-time.

### Global Asynchronous Work

Our platform leverages global talent with 100% asynchronous, merit-based infrastructure, allowing contributions anytime, anywhere.

### Open Source Innovation

UbiquityDAO is fully open-source, continuously enhanced by the global developer community.

### XP-Powered Governance

Our unique XP system tracks contributions, boosting transparency and refining decision-making within DAOs.

### Seamless Stablecoin Integration

Ubiquity Dollar, pegged to the US Dollar, enables seamless transactions. Explore innovative financial solutions like Ubiquity Card (Beta) and upcoming Ubiquity Credit for unsecured loans.

### Open Ecosystem

Fully extensible framework allows you to design custom autonomous agents tailored to your organization’s unique needs.

Discover the future of DAO work with UbiquityDAO.

**Comment by Keyrxng** [comment]
@0x4007 rfc

I thought just comment it here and it can be easily edited by yourself or others

**Comment by 0x4007** [comment]
I think it's a solid post. Just remove the crossed out content and provide a space between Ubiquity and DAO

Ubiquity DAO

---

It doesn't need to be 100% perfect. It highlights some of the tasks which is great. Is it useful to also explain the [DevPool directory](https://devpool.directory)? 

We can also provide links to the [DevPool flow](https://dao.ubq.fi/devpool-flow) etc

**Comment by Keyrxng** [comment]
@0x4007 I have touched it up and included those additional links without dragging anything out

> I can send the needed cash, just let me know how much and you can handle the post?

Happy to do that and handle anything that's needed going forward with it. As for the payout and cash prizes etc you just let me know what to do there. $1k between 10 over 3 months seems like a good trial I think but it can be anything

**Comment by Keyrxng** [comment]
https://dorahacks.io/daobounty/462

**Comment by 0x4007** [comment]
Perhaps a bit too generous with the reward but I guess it's fine for now. I would've expected no more than ~200 wxdai
