### ISSUE TITLE
Recruitment: Curta Puzzle

### ISSUE THREAD

**Issue by Keyrxng** [ubiquity/.github#117]
## Riddle me this: How do we attract quality engineers? 

We need to put ourselves in front of them and noticeably. So I'm proposing that we leverage [Curta](https://www.curta.wtf/), which is like a Solidity Puzzle platform that attracts top quality talent that take part often as well as create them. It done rounds on X in a lot of circles I'm sure you will have heard of it.

> Curta is a talent discovery competition platform and community of protocol engineers.

## What would it require?

Someone be able to create a genuinely novel and (up for debate) difficult EVM based puzzle. So the assignee would need to be extremely well-versed in Solidity and with it's inner workings so this is not an entry level task.

## Why do it?

1. It's a common hiring method to create challenges that aim to filter talent pools
2. It's an advanced talent pool which, with any traction, would pull some our way for sure
3. It puts our name in front of more devs in a very relevant and specific context naturally creating interest "who are they and why is this so fcking hard to complete" - "who are they because I've just earned $1k from a random task" etc...

## Thoughts

1. It will create hype on X for sure when (if, which could be leveraged even still) they are discovered if we could create a wallet and store the private key in the puzzle (maybe a couple) and then the first people to submit the solution we create them a permit to either a wallet of their choosing or the wallet we created.
2. Use the opportunity to highlight the DAO, maybe not in a "come work for us" sort of way but as a sort of fun but serious player (requires a fcking top tier puzzle) and maybe the prize winners or even the runner-ups will be naturally inclined to solve more of our puzzles (tasks)

EDIT: 

highlighting the DAO - this could be a number of ways obviously maybe the devrel/referral stuff could be used here. I'm not 100% on how it works but basically they earn commission on tasks which the dev that they referred to us completes? Just a suggestion, lots of possibilities

**Comment by 0x4007** [comment]
This is a cool idea but our recruiting strategy should focus on TypeScript developers as we have many more TypeScript related tasks in the pipeline. Our current Solidity needs can be handled by our existing developers. 

Perhaps there is a similar idea/platform but for TypeScript developers?

**Comment by Keyrxng** [comment]
There is https://typehero.dev/ that I know of but we cannot create challenges here, good fun though.

I am not aware of others and have not actively looked into it but yeah I'm sure there will be similar Web2 platforms we could leverage no doubt
