### ISSUE TITLE
Optimism Grant: i. basics (tbd)

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/.github#26]
- [ ] name and contact info
- [ ] L2 recipient address
- [ ] how many users in the current eco system
- [ ] demo link and login
- [ ] list competitors and basic SWOT analysis
- [ ] link to code audits (if any)

**Comment by pavlovcik** [comment]
p0
<1 day

**Comment by Hodlatoor** [comment]
https://www.notion.so/ubiquitydao/OP-Grant-770565a361844f299b79e94e97d067dc

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0xfdea701e4ca0d55a095cda4326b8c868a5844d86c459c19b113a5b3227362db7
https://etherscan.io/tx/0x4fa553b98f2988e0b488be42be32eb0ad5423e1c54084a6286556d21282c238f
