### ISSUE TITLE
Optimism Grant: ii. rapport build up: (tbd)

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/.github#27]
- [ ] About the founder(s)
- [ ] Team bios
- [ ] past project links, Github repository, or any other useful information.

**Comment by pavlovcik** [comment]
p0
<1 hour

**Comment by pavlovcik** [comment]
@Hodlatoor it wont take more than a day because the bios are basically done. You should know about this page because you created it 

https://dao.ubq.fi/the-team

We are anon so we wont add much more info about our backgrounds

**Comment by Hodlatoor** [comment]
I wrote the preamble. copy pasted the list. which needs to be updated right?

I was thinking more in terms of actual Bios. Not 2 lines but your call.

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0x93659f167aeab168787e41e3657dcac548d3a82446fc7fde90962445b46a3705
https://etherscan.io/tx/0x008924b1510e00dda0c4964e03be07ece18970a02577e8e6f7be47f49bc778b0
