### ISSUE TITLE
Optimism Grant: iii. basic data (tbd)

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/.github#28]
- [ ] Roadmap and Distribution Plan
- [ ] Current metrics such as TVL, transactions, volume, unique addresses, dune analytics if possible.

**Comment by pavlovcik** [comment]
p0
<1 day

**Comment by sergfeldman** [comment]
@Hodlatoor Please review and provide the comments on Notion 
https://www.notion.so/ubiquitydao/Optimism-Grant-iii-basic-data-5aefd1650ad843bcbbe4ce8e09e9032f

**Comment by Hodlatoor** [comment]
@sergfeldman good job!

**Comment by pavlovcik** [comment]
> @sergfeldman would you please post your wallet address here?

I was handling payouts but yes please post your wallet address so I can send manually.

**Comment by sergfeldman** [comment]
> @sergfeldman good job!

@Hodlatoor Thank you for the feedback!

**Comment by sergfeldman** [comment]
> > @sergfeldman would you please post your wallet address here?
> 
> I was handling payouts but yes please post your wallet address so I can send manually.

@pavlovcik There is no need to pay for this bounty because this is a common task that is a part of my responsibilities

**Comment by pavlovcik** [comment]
Thanks @sergfeldman but I want to ease everybody into this system for compensation. Enjoy the double dipped pay for now 😆

**Comment by sergfeldman** [comment]
> Thanks @sergfeldman but I want to ease everybody into this system for compensation. Enjoy the double dipped pay for now 😆

@pavlovcik Thank you very much!

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0x9c215c11861d7cc97d729142fce69221a649b6dfb816998323afdad0e618a3c6
