### ISSUE TITLE
Optimism Grant: v. Grant strategy (tbd)

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/.github#30]
- [ ] Grant Request outline
- [ ] justifying request for 250k OP (max value)
- [ ] Roadmap and Distribution Plan. specifically over what period of time will the tokens be distributed for each initiative.
- [ ] Outline why each of the initiatives in the roadmap align with the problem statement this proposal is solving.
- [ ] Provide benchmark milestones for the project. These milestones should guide the Optimism community on the progress of the project throughout your work on the project.
- [ ] Define critical milestones for this project. Critical milestones are meant to show goodfaith efforts to accomplish the project.

**Comment by Hodlatoor** [comment]
@sergfeldman Can you take a look at the grant and the points in this issue.  focusing on further defining benchmarks and milestones. They want to feel comfortable seeing progress and payments will be made by them accordingly. 
https://www.notion.so/ubiquitydao/OP-Grant-770565a361844f299b79e94e97d067dc

Thanks!

**Comment by sergfeldman** [comment]
@Hodlatoor I apologize! I missed this comment and that this task is assigned to me.
I will do it as soon as possible.

**Comment by sergfeldman** [comment]
> @sergfeldman Can you take a look at the grant and the points in this issue. focusing on further defining benchmarks and milestones. They want to feel comfortable seeing progress and payments will be made by them accordingly. https://www.notion.so/ubiquitydao/OP-Grant-770565a361844f299b79e94e97d067dc
> 
> Thanks!

@Hodlatoor I have read the grant proposal and I have a few comments. I'll think a little and put them to the Notion.

**Comment by Hodlatoor** [comment]
@sergfeldman Hi Serg, all good here? no more updates as you see?

**Comment by sergfeldman** [comment]
@Hodlatoor Hey, excuse me again for the delays! 

I took the time to read the grants that were submitted to the Optimism program and the Optimism ecosystem to understand their logic.

Raw observations at the moment:
- Activity on the Optimism network is highly dependent on their reward program 
- Their community is more likely to actively support "fun" projects than "serious" projects
- I would not evaluate that they have a very active community of developers, although the development of Optimism itself is quite active

I need some more time to form my thoughts on our grant.

**Comment by sergfeldman** [comment]
@pavlovcik @Hodlatoor As a result of my brief research ^, I would propose to more clearly describe the benefits of DevPool as a way to improve developers' collaboration and community building for Optimism.

It would be good to describe the specific steps in the grant application as well. 
It can be
- Offer Optimism itself to place a certain amount of bounties on preferential terms.
- Pay additional bonuses in the granted OP tokens for those developers who completed the bounty of Optimism itself.
- Provide bounties in the granted OP tokens for the cross-review of bounties and PRs between developers from different projects on Optimism. 
- And other activities that use bounties for collaboration and community building.

**Comment by Hodlatoor** [comment]
@sergfeldman I think those are good ideas. we should simplify them so they are more readily transparent and append to the grant.

**Comment by sergfeldman** [comment]
> @pavlovcik @Hodlatoor As a result of my brief research ^, I would propose to more clearly describe the benefits of DevPool as a way to improve developers' collaboration and community building for Optimism.
> 
> It would be good to describe the specific steps in the grant application as well. It can be
> 
> * Offer Optimism itself to place a certain amount of bounties on preferential terms.
> * Pay additional bonuses in the granted OP tokens for those developers who completed the bounty of Optimism itself.
> * Provide bounties in the granted OP tokens for the cross-review of bounties and PRs between developers from different projects on Optimism.
> * And other activities that use bounties for collaboration and community building.
> 
> What is your opinion?


@Hodlatoor I have added this thought in various ways to the several relevant points in the grant application :)

**Comment by Hodlatoor** [comment]
good work!

**Comment by sergfeldman** [comment]
To claim later

**Comment by sergfeldman** [comment]
Errors prevent me from getting this bounty.
This time https://github.com/ubiquity/pay.ubq.fi/commit/f02eb79
![Claim error](https://github.com/ubiquity/.github/assets/15567379/c3f5c235-671b-45f6-819b-084c10b8dbf0)

**Comment by pavlovcik** [comment]
Need to top up that wallet actually but [here's the fixed link](https://pay.ubq.fi/?claim=eyJwZXJtaXQiOnsicGVybWl0dGVkIjp7InRva2VuIjoiMHg2QjE3NTQ3NEU4OTA5NEM0NERhOThiOTU0RWVkZUFDNDk1MjcxZDBGIiwiYW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm5vbmNlIjoiMTA3NDEzMjc1ODk4OTM0MzQ2MTMyMTE3Nzc3MDA4MTQzODI5NTA5MDQ0NjQ2NTQ1Nzk0MDQwNDMwNjY1NDg2NDgyMDYyMzI4NzIzNTM5IiwiZGVhZGxpbmUiOiIxMTU3OTIwODkyMzczMTYxOTU0MjM1NzA5ODUwMDg2ODc5MDc4NTMyNjk5ODQ2NjU2NDA1NjQwMzk0NTc1ODQwMDc5MTMxMjk2Mzk5MzUifSwidHJhbnNmZXJEZXRhaWxzIjp7InRvIjoiMHgxNkIyNDMzYjlDRjVGRjg3ZEUwM2REYUVlYTYyN0M5MTA2RWUxMTdhIiwicmVxdWVzdGVkQW1vdW50IjoiMjAwMDAwMDAwMDAwMDAwMDAwMDAwIn0sIm93bmVyIjoiMHhmODdjYTQ1ODNDNzkyMjEyZTUyNzIwZDEyN0U3RTBBMzhCODE4YUQxIiwic2lnbmF0dXJlIjoiMHgyZmZlNjBiMWIyYmRlOTdmNGZlNzgwMTgxMzcwMjJhZmI1NjUzYjVmM2JmMDgwZWE3ZWZiN2VmNTQ0MjI5MDc1MjcwMDVlN2M2YzA1YmM3OTcwMTc5MjMzMzc0NDRlNGY3NDFlYzlmNWU4N2Q3OGFkZjdhMDg3NmY1MmJkMWI2OTFjIn0=&network=1).

**Comment by sergfeldman** [comment]
@pavlovcik Thank you! Please, let me know when I can claim it

**Comment by sergfeldman** [comment]
Claimed
