### ISSUE TITLE
Optimism Grant: v. Plenary grant questions to answer

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/.github#31]
- [ ] What problem do we solve for the Optimism ecosystem?
- [ ] How does our value proposition solve the problem above?
- [ ] How this solution will be a source of growth for the Optimism ecosystem?:
- [ ] How committed are we to building on Optimism?

**Comment by pavlovcik** [comment]
p0
<1 day

**Comment by Hodlatoor** [comment]
https://www.notion.so/ubiquitydao/OP-Grant-770565a361844f299b79e94e97d067dc?pvs=4

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0xb2b65bec388551cc7d7c65db837c6fb3007f5a8c35ca2cd9db2efa706e42ebe8
https://etherscan.io/tx/0xdf951d58bce69514e2b16bee4a09c19451a1318f768981a7873022e3d86ba495
