### ISSUE TITLE
DevPool Intro Video: develop video narration wireframe from a first impression perspective

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/.github#34]
develop overview wireframe of DevPool intro video

**Comment by Hodlatoor** [comment]
Video script and wireframe:

1. Welcome to DevPool, a Ubiquity Labs product. Brought to you by Ubiquity DAO.

2. DevPool is Ubiquity’s solution to help get projects done faster. DevPool is built by developers, for developers. DevPool is the crypto native platform that is organically meshed into GitHub to get your projects done faster, cheaper and better while helping developers get more work!


[maybe a visual of cartoon stuck repo manager icon, exclamation point, setup bounty, dev cartoon picks it up. Stuck repo manager happy, project works, dev happy $ sign]

3. DevPool helps you speed up project completion times. 
[show this]
Setup open tasks and assign them a deadline and payment ( We call that a Bounty)


4. DevPool then helps match the right people for the right job. Developers see your Bounty and lock it up. One developer per task. Since DevPool is on Github, you can see prior contributions before accepting the developer. Not only is DevPool fast, it is secure. You only pay when you approve their work. 

You can add bonus pay to develop complicated or sticky tasks. The right bounty hunter will get it done for you.

5. See all your Bounty projects and track their progress. Pay automatically in crypto (alongside bonus Ubiquity Dollar incentives).

Increase your developing capacity without increasing your overhead. Join DevPool today!
			[link]

**Comment by Hodlatoor** [comment]
added po

**Comment by pavlovcik** [comment]
https://etherscan.io/tx/0xad2ca6e98fdfb4f5e9600428b02c60baaaf0514dd22f1d2ed9e36c830dfa3d27
