### ISSUE TITLE
DevPool intro Video: 3-5 points highlight points 

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/.github#35]
think of the 3-5 points you want to highlight to a bounty issuer and bounty hunter about the system. let me know what they are and you can take a SC or vid of each. no need for voiceover.
highlight the most important and useful aspects for a bounty issuer and a hunter.

**Comment by Hodlatoor** [comment]
these are good!

**Comment by Hodlatoor** [comment]
@sergfeldman how are we looking with the videos and mock ups?

**Comment by sergfeldman** [comment]
> @sergfeldman how are we looking with the videos and mock ups?

@Hodlatoor It turned out that features that have not yet been implemented are difficult to record on video even with mocks. I continue thinking about how to show them.

Please review the fake screenshots below and tell me if I should change something. Thank you!

**Comment by sergfeldman** [comment]
Setting up the bounty price
![Bounty automation 01 3 28 2023](https://user-images.githubusercontent.com/15567379/228365655-0a1c6c8d-9213-44b3-8c8e-11b1ce791fe9.JPG)

Bounty-Developer matchmaking - comment with an invitation to take the bounty
![Bounty automation 02 3 28 2023](https://user-images.githubusercontent.com/15567379/228365686-61528bd9-4344-42f8-98ce-8bb88b3bb79d.JPG)

Bot commands / help, /assign
![Bounty automation 03 3 28 2023](https://user-images.githubusercontent.com/15567379/228365720-0f30ea08-5d96-4e79-b87d-39c5eb45b72b.JPG)

Bot command /wallet
![Bounty automation 04 3 28 2023](https://user-images.githubusercontent.com/15567379/228365753-e1c52676-15bb-4869-9175-4e5f81f228de.JPG)

Reminders to the bounty hunter in the comments
![Bounty automation 05 3 28 2023](https://user-images.githubusercontent.com/15567379/228365785-2c51e59f-646d-48a5-bf17-d1c3355c27eb.jpg)

Claim the payment after done bounty and get paid 
![Bounty automation 06 3 28 2023](https://user-images.githubusercontent.com/15567379/228365812-47b9164f-0c39-4acf-9277-fb8e34f7f44a.jpg)

**Comment by Hodlatoor** [comment]
@sergfeldman yes, these look good. let's proceed with them!

**Comment by sergfeldman** [comment]
@pavlovcik @Hodlatoor Hey, please watch the video.

It is worth bearing in mind that
1. I strive to show all the main UbiquiBot automation points.
2. Some comments should be placed by UbiquiBot, but since they are not implemented, I copied mocks and posted them myself.
3. Some messages from the UbiquiBot are duplicated, this needs to be fixed.
4. If the logic is right, then we need to trim the moments from the video when I copy the mocks from the file.

I would be grateful for feedback.

https://user-images.githubusercontent.com/15567379/228657687-72d5a5f9-7aae-48d5-b394-31d354c5ec42.mp4

**Comment by pavlovcik** [comment]
Its definitely a good start! Superficially I wish that: 
1. you could zoom in ("ctrl" + "+") to utilize the empty space on the left and right sides. 
2. I wish you were on MacOS so that the text renders more clearly lol

**Comment by Hodlatoor** [comment]
the points are good. (@sergfeldman the images are blurry)
@pavlovcik the video is good but 2 minutes.    we're shooting for 12 seconds.

looking at the different video generation services, I am wondering we should have @pavlovcik take the video of the features we all outlined, in one shot, close to 12 seconds, post here and I will try and integrate that with the narration of the text in the wireframe with proper timing.

**Comment by sergfeldman** [comment]
@pavlovcik @Hodlatoor Thanks for the recommendations! 
I re-recorded the video to fulfill them.

Which direction is better?

16 seconds (can be reduced to 12)

https://user-images.githubusercontent.com/15567379/228829878-ace50c40-b684-4f20-87ea-c8ac68b3dd05.mp4


7 seconds (can be reduced to 6)

https://user-images.githubusercontent.com/15567379/228829927-8e1299c6-eb49-445c-abdd-f93d831f0003.mp4

**Comment by pavlovcik** [comment]
> Which direction is better?

I like the first video because it stops and highlights points. 

I wish you were able to use smooth scrolling. This might be based on your mouse hardware.

**Comment by sergfeldman** [comment]
> > Which direction is better?
> 
> I like the first video because it stops and highlights points.
> 
> I wish you were able to use smooth scrolling. This might be based on your mouse hardware.

@pavlovcik @Hodlatoor In this version of the recording, I used a different scroll and a fast pace to suit into 12 seconds

https://user-images.githubusercontent.com/15567379/229772758-38204ab8-3062-4924-9abf-1c28321a7cf9.mp4

**Comment by Hodlatoor** [comment]
@sergfeldman i like it.
@pavlovcik can we use this and proceed to video assembly?

**Comment by Hodlatoor** [comment]
nice work!

**Comment by sergfeldman** [comment]
@pavlovcik Just to be clear - I took this wallet ^ for the demo purpose from our examples.

![Wallet from the example](https://user-images.githubusercontent.com/15567379/232334808-7e13213f-1a0f-4721-9adf-705963783d7a.JPG)

If you want to pay me for this issue, then my wallet for DAI
0xC3fdC486EEa63D7960e50CC5409fbeA434a6fDf3

**Comment by sergfeldman** [comment]
Claimed

**Comment by pavlovcik** [comment]
You should leave your assignment after completion for analytics/audits on completed tasks @sergfeldman
