### ISSUE TITLE
DevPool intro Video: final cut

### ISSUE THREAD

**Issue by Hodlatoor** [ubiquity/.github#37]
roll out the v1 demo reel!

**Comment by Hodlatoor** [comment]
@pavlovcik 
tried AIstudio, pictory and deep brain. not impressed.
https://www.synthesia.io/pricing seems to be better but if you have a better venue do let me know

**Comment by pavlovcik** [comment]
> "devpool"

You can try writing it as "dev pool" in the script. I'm sure that will pronounce accurately.

---

To be honest I would much rather focus on the screen recordings as the primary content, and then record with my (or your) Anata for any B roll. Showing a random human signals grift in this industry. Anata, or another NFT project on the other hand is a green flag.

**Comment by Hodlatoor** [comment]
yeah i was going to try dev pool but can't do that in the demo anymore. have a feeling it will be DEEv though. we'll find out.
I was also thinking of using our anatas but i am not sure how to integrate the vrm into their platform. will email them.
otherwise if we do our own narration with an anata can try and superimpose that on the video walkthrough

**Comment by Hodlatoor** [comment]
want to give https://www.hologram.xyz/download a try on your browser+webcam?

**Comment by pavlovcik** [comment]
> want to give https://www.hologram.xyz/download a try on your browser+webcam?

Unfortunately I need to be at an office type setup due to 1. battery means my Mac runs in low power mode which yields low fps. 2. sound

**Comment by Hodlatoor** [comment]
finished up in notion page

**Comment by Hodlatoor** [comment]
master wallet issue

**Comment by pavlovcik** [comment]
> master wallet issue

You don't need to regenerate payment permits if there's issues with the permit wallet actually. Although technically all permits [have an expiration time](https://github.com/Uniswap/permit2/blob/main/src/interfaces/ISignatureTransfer.sol#L33), we set ours to be very far in the issue where it is a non issue.
