### ISSUE TITLE
Copywriting & Narrative Design

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/.github#6]
### Context

Plain English explainers on context of our initiatives in https://github.com/ubiquity/.github/issues/3

### Priority of Copywriting

- [ ] #7
- [ ] #8

### Priority of Narratives 

- [ ] Ubiquity DAO
- [ ] [Ubiquity DevPool](https://dao.ubq.fi/devpool)
- [ ] [UbiquiBot](https://github.com/ubiquity/bounty-bot)
- [ ] [Ubiquity Dollar](https://github.com/ubiquity/ubiquity-dollar)
- [ ] [Ubiquity Bonds](https://github.com/ubiquity/ubiquity-dollar/wiki/13.-Bonding)
- [ ] [Ubiquity Vaults](https://github.com/ubiquity/ubiquity-dollar/wiki/12.-Yield-Aggregator)
- [ ] [Ubiquity Cashback Rewards](https://github.com/ubiquity/ubiquity-dollar/discussions/158)
- [ ] [UbiquiStick](https://github.com/ubiquity/ubiquity-dollar/wiki/15.-UbiquiSticks)

### Content Strategy

- [ ] "Humanize" the DAO. Stories of contributors.

**Comment by pavlovcik** [comment]
To produce bounties will need two parameters: 1. estimated time/deadline to complete 2. priority level

**Comment by pavlovcik** [comment]
@Obfuscatoor

**Comment by Hodlatoor** [comment]
I think we start with the topline story we have. It starts the narrative in a humanized style.

- setup telegram chat with the devs. want to hear their perspectives. (couple of hours)
- finish article.  (about 10 hours total) 

after that comes analysis of the different components we want to outline and how in depth / pedestrian we want them to be. I think helicopter view should be fine for the narratives and then linking to more technical documents for readers wanting to dive in more.

**Comment by pavlovcik** [comment]
> * finish article.  (about 10 hours total)

Mate use gpt3 it'll take like 1 hour lol

**Comment by Hodlatoor** [comment]
yeah... qualitiii:

Jon G
write a professional and insightful article about why ubiquity DAO is unique

Ubiquity is a decentralized autonomous organization (DAO) that aims to democratize the world of real estate investment by allowing anyone to invest in commercial real estate using cryptocurrency. But what makes Ubiquity unique?

One of the key features that sets Ubiquity apart is its use of blockchain technology. By utilizing the Ethereum blockchain, Ubiquity is able to offer a transparent and secure platform for real estate investment. All transactions are recorded on the blockchain, ensuring that they are transparent and verifiable. This level of transparency is not possible with traditional real estate investment methods, which can be opaque and prone to fraud.

Another unique aspect of Ubiquity is its focus on commercial real estate. While there are other real estate investment platforms available, many of them focus on residential properties. By focusing on commercial properties, Ubiquity is able to offer investors access to a different class of assets with potentially higher returns.

In addition to its focus on commercial real estate and use of blockchain technology, Ubiquity also has a unique governance model. As a DAO, Ubiquity is run by its community of token holders, who are able to vote on key decisions affecting the organization. This decentralized governance structure gives token holders a say in how the platform is run, and ensures that the interests of the community are prioritized.

Overall, Ubiquity is a unique platform that combines the transparency and security of blockchain technology with the potential for high returns in the commercial real estate market. Its decentralized governance model also sets it apart from traditional real estate investment platforms, offering token holders a say in the direction of the organization. These features make Ubiquity an exciting and innovative player in the world of real estate investment.



---
this dreck is worse than jeeting the article lol

take a look at the updated article.  there's a green remark in there for you if you want to add /remove it.

https://docs.google.com/document/d/1NBWEXiBKwwisAOpGL7-F_rSi0neUa8WZzTnaLPZGsUY/edit?usp=sharing
