### ISSUE TITLE
Maybe we can offer a job to wannacfuture and vennox to help with our reviews/qa/deploys? @Draeieg

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/.github#77]
Maybe we can offer a job to wannacfuture and vennox to help with our reviews/qa/deploys? @Draeieg 

_Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/pull/422#issuecomment-1603936984_

**Comment by pavlovcik** [comment]
In a rush now wanted to record but didn't know how to add a draft on the project view from mobile.

**Comment by Draeieg** [comment]
> Maybe we can offer a job to wannacfuture and vennox to help with our reviews/qa/deploys? @Draeieg 
> 
> _Originally posted by @pavlovcik in https://github.com/ubiquity/ubiquibot/pull/422#issuecomment-1603936984_

I see no downside if you think their code is good, we ship more and I can get my own QA team lol
