### ISSUE TITLE
UBQ Contributor Airdrop

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/.github#90]
Make a command line tool that will tally up everybody's contributions from the last year. 

We can parse all the permits generated across all of our repos and then drop 1 UBQ per dollar earned. 

We should run this script when we enable UBQ token payouts

**Comment by b4s36t4** [comment]
@pavlovcik Would love to work on this. Can you explain more on this?

**Comment by pavlovcik** [comment]
- Use @ubiquity/ts-template
- go through every closed as completed issue and tally up the payments for every contributor 
- output results in a csv

**Comment by b4s36t4** [comment]
Cool, Will do that.

/start

**Comment by EtherealGlow** [comment]
@pavlovcik can I do this?

**Comment by pavlovcik** [comment]
Sure just be sure to make it in typescript, using @octokit/rest, and it's executable using tsx. 

You will need to print test results as part of the pull request QA or it will not be accepted.

**Comment by EtherealGlow** [comment]
its halfway done 
https://github.com/EtherealGlow/ContributionAnalyzer

**Comment by EtherealGlow** [comment]
![Screenshot_2023-12-27_17-46-38](https://github.com/ubiquity/.github/assets/139999816/c6d443c2-d94e-402e-80e3-89456d315986)
The analyzer was able to find the 175 dollars of the total contribution on this repo but what about issues which have had their price label removed

**Comment by pavlovcik** [comment]
The spec states to parse permits not labels.

**Comment by EtherealGlow** [comment]
how can i qa this, it seems mostly done just need to convert to a csv file

**Comment by pavlovcik** [comment]
Just need to see results and they will be spot checked I don't understand the confusion

**Comment by EtherealGlow** [comment]
Ubiquibot isn't working for me, I can't create test payment links for a test repo and scan them using this

**Comment by pavlovcik** [comment]
There's plenty of permits that exist on the Ubiquity repositories. You don't need to generate any.

**Comment by EtherealGlow** [comment]
heres what the command line tool gave me for this [issue](https://github.com/ubiquity/ubiquibot/issues/773)
[output (3).xlsx](https://github.com/ubiquity/.github/files/13791617/output.3.xlsx)

**Comment by pavlovcik** [comment]
Seems fine just ideally should link the original permit comment in the next column, then of course go through every repository in the ubiquity org

**Comment by EtherealGlow** [comment]
I am assuming 3 minutes is a normal amount of time for scanning a entire repo

**Comment by EtherealGlow** [comment]
Also which repos do I have to scan (I have already scanned ubiquibot)

**Comment by EtherealGlow** [comment]
[ubiquibot.csv](https://github.com/ubiquity/.github/files/13795972/ubiquibot.csv)
until then, heres the csv for the ubiquibot repo

**Comment by pavlovcik** [comment]
> [ubiquibot.csv](https://github.com/ubiquity/.github/files/13795972/ubiquibot.csv)
> 
> until then, heres the csv for the ubiquibot repo

I think just link the comment instead of all those permits. 

You'll need to dynamically get every repo under ubiquity and compile the rewards.

**Comment by EtherealGlow** [comment]
Aight wait a bit

**Comment by EtherealGlow** [comment]
[output (9).csv](https://github.com/ubiquity/.github/files/13797392/output.9.csv)

**Comment by EtherealGlow** [comment]
done

**Comment by pavlovcik** [comment]
It needs to go through every repo

**Comment by EtherealGlow** [comment]
It did

**Comment by EtherealGlow** [comment]
For the repo part I am using
 GET /orgs/{name}/repos

**Comment by EtherealGlow** [comment]
https://github.com/EtherealGlow/ContributionAnalyzer/blob/development/src%2Fhelpers%2Fissue.ts#L108-L122

**Comment by EtherealGlow** [comment]
@pavlovcik

**Comment by EtherealGlow** [comment]
Man I wish this gets completed today because tomorrows new years

**Comment by EtherealGlow** [comment]
@pavlovcik should I make a any changes to this or no?
I think it works flawlessly

**Comment by pavlovcik** [comment]
I'm currently traveling for new years but I'll check on my computer this week

**Comment by pavlovcik** [comment]
https://github.com/EtherealGlow/ContributionAnalyzer/pull/2/files#diff-12060c1ccac042edab175ad9fa0c53086a60c5d666978c11d00772ae379c2535R46

This approach seems problematic. You should figure out a more robust way to test the comment for links to pay.ubq.fi because I don't believe that every permit has this exact header?

**Comment by EtherealGlow** [comment]
@pavlovcik please check out the repo

**Comment by pavlovcik** [comment]
I didn't see you open a PR with the fixes I mentioned that are necessary so what are you referring to?

**Comment by EtherealGlow** [comment]
Oh I have to open a pr to your fork??

**Comment by pavlovcik** [comment]
Any code changes should link back to this issue for auditing purposes.

**Comment by EtherealGlow** [comment]
https://github.com/ubiquity/contribution-analyzer/pull/1/commits/f1ed4a7a58c3c39069ee0208d71ba34d4f4867ff

**Comment by EtherealGlow** [comment]
This should work, I didn't have the wallets address of people

**Comment by EtherealGlow** [comment]
@pavlovcik

**Comment by EtherealGlow** [comment]
@pavlovcik for this commits qa I check internally on my own repo on which it worked, I couldn't test it on the ubiquity repo because I don't have the wallet addresses of the members, how do you suggest I qa this?

**Comment by pavlovcik** [comment]
Here's a backup:
```
"user_name", "wallet_address", "created_at", "updated_at"
seprintour	0x3623338046b101ecEc741De9C3594CC2176f39E5	2023-04-21 13:23:49	2023-04-21 13:23:49
pwilson77	0x639EeCAA3418AfbAB34A3c5B44cC14A9045D7429	2023-04-23 13:14:14	2023-04-23 13:14:14
Steveantor	0x4841e8153a7b9E8B1F218E42d3cBaEb3e99C28eE	2023-03-28 07:19:43	2023-05-05 10:16:50
zgorizzo69	0x10693e86f2e7151B3010469E33b6C1C2dA8887d6	2023-05-12 16:55:06	2023-05-12 16:55:06
eugenioclrc	0xD75943B4d35770AC8e6E1Ebe26F483DC5282d2AD	2023-05-17 14:14:30	2023-05-17 14:14:30
rotcivegaf	0xDD7Fa234BcF98B71dB490A6d074FA18865c681A4	2023-05-19 16:18:23	2023-05-19 16:18:23
devpanther	0xf76F1ACB66020f893c95371f740549F312DEA3f1	2023-04-09 03:59:48	2023-07-28 09:52:21
web4er	0x1F9FCc0E84dc2094499b848AE37Cd6a51db03Ff2	2023-06-29 11:58:23	2023-07-05 21:44:53
Wholesomebruh	0xD76e43a789489D66Bb5CE56304fC8bb2A084F9F5	2023-08-01 11:48:52	2023-08-01 11:48:52
b4s36t4	0xCee33C98410DEbe67A319Cb94F39e403435Df319	2023-07-06 17:01:46	2023-07-06 17:01:46
QuintusTheFifth	0x7b3813a943391465Dd62B648529c337e52FbA79b	2023-06-03 23:50:10	2023-06-03 23:50:10
harjaapdhillon16	0x9d4b1a2c56364532b6006d214dba3fe6e89da5ad	2023-06-04 10:55:46	2023-06-04 10:55:46
sweetapplepumpkinpie	0xceb35ce20527b4371f0a9a72f0a1a133075e4aef	2023-06-05 15:40:06	2023-06-05 15:40:06
Venoox	0x999cc482d3b04dd3dF733411687341906989Ec5B	2023-06-05 20:19:09	2023-06-05 20:19:09
AnakinSkywalkeer	0x2bBc6a8314044d70684C74CfA0E117eb75E3708c	2023-06-11 20:52:48	2023-06-11 20:52:48
Draeieg	0xb87d1713f2fade89fe9de557a2e37d10f006a5d1	2023-05-16 22:20:05	2023-06-13 03:47:29
h918m	0x19275E9fD721906F2715D4b78681b49da5088117	2023-06-14 08:08:28	2023-06-14 08:09:30
sergfeldman	0x16B2433b9CF5FF87dE03dDaEea627C9106Ee117a	2023-03-28 20:27:09	2023-07-09 22:41:23
whilefoo	0xA0B11F474d8ECE1205d38c66d5F2bE8917675d60	2023-07-11 17:50:27	2023-07-11 17:50:27
rndquu	0x336C033842FA316d470e820c81b742e62A0765DC	2023-04-11 07:17:56	2023-08-01 16:01:31
tungbq	0xaa13387810931252811186Ff05a467194E41341C	2023-08-01 16:12:26	2023-08-01 16:12:26
aditygrg2	0xB951653877b7D6c9AB26bf5E7f30708fC76f53E0	2023-08-04 17:12:46	2023-08-04 17:12:46
sudotx	0xFEe153CE18Ffb3291011f8cB62C37626230aA62F	2023-08-07 10:29:16	2023-08-07 10:29:16
Sadaf-A	0x0BEd00438D57d07E3667b85Fa8EB86Af147C7025	2023-08-10 17:04:50	2023-08-10 17:04:50
molecula451	0x4D0704f400D57Ba93eEa88765C3FcDBD826dCFc4	2023-06-16 17:28:33	2023-06-16 17:28:33
gitcoindev	0x7e92476D69Ff1377a8b45176b1829C4A5566653a	2023-06-19 09:50:54	2023-06-19 09:50:54
		2023-07-14 08:06:25	2023-07-14 08:06:31
starlitnightsky	0x8c8b5eeea2770e795f2814e802e335bdb9e5a3b0	2023-06-20 00:38:05	2023-06-20 08:50:47
diamondnegroni	0xB49c891C1e1E693958d11F27a920Fee343aEb68d	2023-06-27 02:43:55	2023-06-27 02:43:56
0xcodercrane	0x00868BB3BA2B36316c2fc42E4aFB6D4246b77E46	2023-03-28 02:25:22	2023-08-14 16:02:18
Keyrxng	0xAe5D1F192013db889b1e2115A370aB133f359765	2023-08-20 08:09:23	2023-08-20 08:09:23
Hodlatoor	0x5c747b83f343f642ad983e3cbea04feb37227dfe	2023-04-08 04:17:30	2023-08-20 12:24:58
Ameralameri	0x20fe9f5896a3021ca6ea78005a15ae954dc134e6	2023-06-28 16:12:40	2023-06-28 16:12:40
umershaikh123	0xe17f7ffB49C70635d3428D4eAAcf76DEa457E150	2023-08-21 11:47:17	2023-08-21 11:47:17
PhantomCracker	0xCAC0A8cF4cc7073b040c7fe6328Da7f229AF40A6	2023-05-24 14:30:48	2023-06-30 10:32:05
devtestubq	0xc4fc63d88dd411b19acf86fb56ba50941611b3a7	2023-07-18 19:03:45	2023-07-18 19:03:45
ByteBallet	0xeFeF11577Db8f882F6Bf92F46008170Ba3602D40	2023-07-27 00:07:07	2023-07-27 00:07:07
byteballet	0x30fDdD8b3f3a4183734884b6d383da6bf4bf2cd1	2023-08-15 07:44:09	2023-09-01 13:34:43
rndquu2	0x1688Ae524968aCa90B75B598aA9065d87c2C9CEF	2023-09-01 17:04:22	2023-09-01 17:04:22
FibrinLab	0x3EFFe91C62d1864C3B791Bc7bbD43b68B899d12A	2023-04-02 06:32:09	2023-09-05 08:31:13
GaryThisSidee	0x2bBc6a8314044d70684C74CfA0E117eb75E3708c	2023-09-09 11:11:17	2023-09-09 11:11:17
pavlovcik	0x4007CE2083c7F3E18097aeB3A39bb8eC149a341d	2023-04-26 11:04:22	2023-09-09 13:11:47
wannacfuture	0x9e4EF4353C928cD3eb473E8f12aeCF58C208ef40	2023-06-03 18:03:55	2023-09-23 12:03:19
me505	0x219d695ff93b443fc3E943BD1052805AF83C6612	2023-06-19 12:05:42	2023-10-04 10:29:46
bojan07	0xc6fa133f3290e14Ad91C7449f8D8101A6f894E25	2023-09-08 10:24:49	2023-10-04 15:06:01
EtherealGlow	0x219d695ff93b443fc3E943BD1052805AF83C6612	2023-07-19 17:34:37	2023-10-23 07:53:09
AlooDon	0x38241902297144Df7C30F7De66963059dB143da2	2023-11-16 13:00:59	2023-11-16 13:00:59
evanjonesxx	0xe2111B76461BE1f3Df2E364Be1b18aAB9e4D2469	2023-11-30 10:02:13	2023-11-30 10:02:13
yeshealer	0xA09f6409c2BA41845a878c37639931980476b47c	2023-11-30 14:46:03	2023-11-30 14:46:03
```

**Comment by EtherealGlow** [comment]
Aight thanks, appreciate it

**Comment by EtherealGlow** [comment]
here
[output.csv](https://github.com/ubiquity/.github/files/14025463/output.csv)

**Comment by EtherealGlow** [comment]
it works now

**Comment by pavlovcik** [comment]
It is missing a lot of permits, including this for the assignee https://github.com/ubiquity/business-development/issues/60#issuecomment-1637052565

**Comment by EtherealGlow** [comment]
It was a pesky case sensitivity bug, squashed it. Heres the result
[output (3).csv](https://github.com/ubiquity/.github/files/14028377/output.3.csv)

**Comment by pavlovcik** [comment]
You need to check your work before submitting it. I can't spend this much time clarifying instructions.

This permit is not in your spreadsheet. https://github.com/ubiquity/business-development/issues/38#issuecomment-1653564466

**Comment by EtherealGlow** [comment]
https://github.com/EtherealGlow/ContributionAnalyzer/commit/696c0748c1f9988dad8338b4d334ad3bb2243450

**Comment by EtherealGlow** [comment]
i painstakingly checked the ones which werent assigned to any hunter, I am 90% sure that the ones that are not assigned to anyone is just because of the wallet addresses not being found

**Comment by EtherealGlow** [comment]
[output (4).csv](https://github.com/ubiquity/.github/files/14041891/output.4.csv)

**Comment by EtherealGlow** [comment]
@pavlovcik

**Comment by EtherealGlow** [comment]
@pavlovcik

**Comment by EtherealGlow** [comment]
@pavlovcik

**Comment by EtherealGlow** [comment]
Also I have a request, whenever you are free can you point out mistakes on how i work, I really want to get a internship by 16 so I wanna improve how I work

**Comment by EtherealGlow** [comment]
It's been 10 days now

**Comment by EtherealGlow** [comment]
@pavlovcik

**Comment by EtherealGlow** [comment]
I am getting hella ignored

**Comment by EtherealGlow** [comment]
I get that I may request too many reviews, will test properly from now on wards but if it has annoyed you to the point of not reviewing, please forgive me.
I am gonna make a script to see if all the permits that were not assigned were due to the reason of a unavailable wallet address

**Comment by EtherealGlow** [comment]
here are the test results
https://github.com/EtherealGlow/ContributionTester/actions/runs/7779558930/job/21210897922

**Comment by EtherealGlow** [comment]
I hope you can review it now 🙏🏼

**Comment by EtherealGlow** [comment]
???

**Comment by EtherealGlow** [comment]
Why did you unassign me

**Comment by pavlovcik** [comment]
> here are the test results https://github.com/EtherealGlow/ContributionTester/actions/runs/7779558930/job/21210897922

There is no CSV of results that I could see there, and this error message doesn't look promising. https://github.com/EtherealGlow/ContributionTester/actions/runs/7779558930/job/21210897922#step:5:7

> I get that I may request too many reviews, will test properly from now on wards but if it has annoyed you to the point of not reviewing, please forgive me. I am gonna make a script to see if all the permits that were not assigned were due to the reason of a unavailable wallet address

I estimated this could be done within a week. For myself, perhaps a few days of work. We're currently beyond two months from when you were assigned. You are disqualified from this continuing on this task. 

> Also I have a request, whenever you are free can you point out mistakes on how i work, I really want to get a internship by 16 so I wanna improve how I work

Bear in mind that like any core Ubiquity team member, I have other responsibilities aside from reviewing your pull requests. My advice to you would be to respect the time of others. Be sure to make the reviewer's job as easy as possible by 1. ensuring that your code works according to the issue specification 2. providing as much clearly written context/explanations with your work in the form of comments on the pull request 3. carefully following the rules at https://dao.ubq.fi/devpool

It is not appreciated that you have continued to abuse our communication channels, such as other pull requests, and our public telegram group chat, by creating sybil accounts and prompting me to review this deliverable over several days.  

Conversation under issues should only be for clarifying the specification. Conversation under your pull request is where deliverable-related conversation occurs. 

I am only posting details (only related to you, and not the issue) here under the issue because you failed to follow the rules and did not link back another pull request with your latest work deliverable.

If you do not follow the rules, the reviewers have no obligation to work with you.

**Comment by EtherealGlow** [comment]
Please forgive me, I'll follow the rules from now on 🙏

**Comment by EtherealGlow** [comment]
The test was for checking all the rouge permit comment links and to see if they weren't assigned to anyone because of missing addresses

**Comment by EtherealGlow** [comment]
You can see in the latest CSV that everything's working correctly

**Comment by EtherealGlow** [comment]
> [output (4).csv](https://github.com/ubiquity/.github/files/14041891/output.4.csv)
> 

Around here

**Comment by EtherealGlow** [comment]
Please let me continue on the task, I already contributed so much

**Comment by EtherealGlow** [comment]
A whole repo and a pull request to fix issues on the repo

**Comment by pavlovcik** [comment]
Closed for clutter on issue comments. Recreated at https://github.com/ubiquity/.github/issues/95

**Comment by EtherealGlow** [comment]
So I can't?
