### ISSUE TITLE
Command-Line Tool Totaling Contributor Rewards for UBQ Airdrop

### ISSUE THREAD

**Issue by pavlovcik** [ubiquity/.github#95]
## Overview

We are looking to develop a command-line tool that automates the tallying of contributions across all Ubiquity repositories for the last year. This tool will play a crucial role in recognizing and rewarding our contributors' efforts through UBQ token payouts.

### Tally Contributions

The tool should accurately parse through all the "permits" (or payments for recognized contributions) generated across our repositories to identify and sum up each contributor's total contributions in terms of dollars earned.

### UBQ Token Calculation

Based on the dollar value of each contributor's total contributions, calculate the equivalent amount in UBQ tokens, with the conversion rate being 1 UBQ per dollar earned.

### Output Format

The results should be compiled into a comprehensive CSV file for each repository, detailing the contributors' names, total dollar earnings, and corresponding UBQ tokens. This CSV file will serve as the basis for UBQ token payouts.

### Automation and Execution
This script should be designed for easy execution at specific times, particularly when enabling UBQ token payouts to ensure a seamless distribution process.

## Requirements
- Use TypeScript for development to ensure type safety and maintainability.
- Utilize the @octokit/rest library for GitHub API interactions to fetch permits across repositories.
- Ensure the tool is executable through `tsx` to facilitate integration into our existing workflow.
- Include a testing mechanism that prints test results, which will be a critical part of the pull request QA process.

## Final Deliverables
- A fully functional command-line tool meeting the above specifications.
- Documentation on how to set up, use, and contribute to the tool.
- Test cases and results demonstrating the tool's effectiveness and accuracy.
- This tool is integral to our efforts to automate and streamline our reward system for contributors. It will not only enhance our operational efficiency but also ensure transparency and fairness in UBQ token distribution.

We look forward to seeing innovative solutions and contributions from the community to bring this project to fruition.

**Comment by CrustalRundrops** [comment]
> Include a testing mechanism that prints test results, which will be a critical part of the pull request QA process.
Can someone elaborate more on this

**Comment by pavlovcik** [comment]
> > Include a testing mechanism that prints test results, which will be a critical part of the pull request QA process.
> 
> 
> 
> Can someone elaborate more on this

An easy way is to write a GitHub action so we can see that it works in the pull request CI.

**Comment by Keyrxng** [comment]
Just seen your comment @pavlovcik, haven't built it with that in mind but should be easily repurposed for a GH action. Can you create a new repo for it and I'll open a PR

- https://github.com/Keyrxng/ubq-airdrop-cli

- https://github.com/Keyrxng/ubq-airdrop-cli/blob/master/all_repos_all_payments.csv

using my cex deposits, my tally is accurate for me after adding in the two no-assignee payments of 300 and 12.50 im at about 1556 ish

cases which I've seen:
- New assignee on an issue that has already been paid out
see: https://github.com/Ubiquity/research/issues/40
200 paid to hodl but pav is now the assigned so it's been assigned to pav in this particular case

- Payments that have been redacted and added as a debt on their next payment
see: https://github.com/Ubiquity/business-development/issues/38
300 paid to hodl but 300 debt added

- deleted GH accounts see: AnakinSkywalker who is now Ghost

Will need to think about how to handle these cases and try to make this more robust

**Comment by pavlovcik** [comment]
Use the ts-template repo GitHub actions for inspiration on how to execute typescript files directly. 

Just parse the permits. Cross reference the address from our database (you can use a snapshot of the wallet data for now) 

Every permit for any contribution counts. They can certainly earn rewards without ever being the assignee via comment incentives.

**Comment by Keyrxng** [comment]
I've been able to identify creator/assignee/conversation rewards from after they were introduced, I went with comment parsing as it seemed more robust in that wallet changes wouldn't affect a hunter's tally.

Only been gone a minute but remind me, are all of the permits stored in the DB?

If going with that approach as opposed to comment parsing then how should I handle:

- Payment made then retracted and debt applied, reduce tally by debt amount or forget it?
- Permit produced then invalidated for whatever reason?
- If payments are to a wallet address not currently registered just forget those?

**Comment by pavlovcik** [comment]
Keep it extremely simple. Only a subset of permits are stored in the database. Don't worry about the penalties. Don't worry about invalidations. Just tally the wallet addresses, don't worry about "registration."

The main challenge here is that the comment/permit encoding schema has changed a few times since we started this system over a year ago. The script needs to handle these changes.

**Comment by Keyrxng** [comment]
![image](https://github.com/ubiquity/.github/assets/106303466/936062b3-546c-434f-b6d6-ff88adeeeb0d)

- https://github.com/Keyrxng/ubq-airdrop-cli/blob/master/all_repos_contributors.csv

> The main challenge here is that the comment/permit encoding schema has changed a few times since we started this system over a year ago

I have covered all the forms of payment comment that I've been able to find, unless their are reviewer reward comments hidden away somewhere which I wouldn't have been exposed to I'm sure I've covered them all.

I have totalled the contributors already but only through comment parsing, what I'll do is build a permit based version and compare the two results I guess.

> Only a subset of permits are stored in the database, so only rely on the address data encoded in the permit.

So the trade off then is that if the db is used then it will cut out large chunk of payments whereas if comments are used the accuracy can't be 100% unless they are all manually reviewed

**Comment by Keyrxng** [comment]
So I've built this as a CLI tool with multiple commands that parses all repos together or singular repos, allows a time be provided to search from, but that's not sounding right now.

So am I correct in thinking that the only function needed really is to be able to parse one singular repo as part of CI meaning on merge or as a CRON job? If so what do you want me to do with the CSV, output that into the action logs or commit it to the repo as files?

> across all Ubiquity repositories for the last year.

Is this a hardcoded date btw if so then when?

**Comment by Keyrxng** [comment]
- https://github.com/Keyrxng/ubq-airdrop-cli/actions/runs/7860439292

The current CLI setup as a GitHub action. I've hardcoded the repo name for the sake of QA but we'd pull that from the repo that it's running in

**Comment by pavlovcik** [comment]
> Is this a hardcoded date btw if so then when?

No we should include every contribution that exists. 

> https://github.com/Keyrxng/ubq-airdrop-cli/actions/runs/7860439292

Looks pretty good I can spot check by cross referencing repositories later.

**Comment by Keyrxng** [comment]
@pavlovcik pr open

**Comment by pavlovcik** [comment]
I'm going to try and salvage the permit link from the logs

**Comment by pavlovcik** [comment]
<details>
	<summary>
		<b
			><h3>
				<a
					href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiIyMjgyMDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIyNDQ3MDIxNTY5NzgzMDA3MzcyNzg0MDA0Nzc0MzUyMzE4ODE5MTU1MDk0NzE1ODc5NTM2MDIyMDExNDIxODQ0MTIyMjg1Nzc0NTgzOSIsImRlYWRsaW5lIjoiMTE1NzkyMDg5MjM3MzE2MTk1NDIzNTcwOTg1MDA4Njg3OTA3ODUzMjY5OTg0NjY1NjQwNTY0MDM5NDU3NTg0MDA3OTEzMTI5NjM5OTM1In0sInRyYW5zZmVyRGV0YWlscyI6eyJ0byI6IjB4NDAwN0NFMjA4M2M3RjNFMTgwOTdhZUIzQTM5YmI4ZUMxNDlhMzQxZCIsInJlcXVlc3RlZEFtb3VudCI6IjIyODIwMDAwMDAwMDAwMDAwMDAwMCJ9LCJvd25lciI6IjB4NDRDYTE1RGIxMDFmRDFjMTk0NDY3RGI2QUYwYzY3QzZCYkY0QUI1MSIsInNpZ25hdHVyZSI6IjB4NTg3OGQ5MTFjNzZmNWUxZDNiY2NlZDQzMmVlYTFiOWRlMTBlM2I3ZjJiNGIyYTNkZGNiNmMxNjQyMDlhMTY5YjQxYTFkMmU4MjMxYzBhODcyODExZWFiYjVkNGFiNjViZTc3MGY0N2ViNmVmZjQ1MWVhYTViNjk0NGM5ZGYyMGUxYiIsIm5ldHdvcmtJZCI6MTAwfV0%3D"
				>
					[ 228.2 WXDAI ]</a
				>
			</h3>
			<h6>@pavlovcik</h6></b
		>
	</summary>
	<h6>Contributions Overview</h6>
	<table
		><thead>
			<tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th> </tr></thead

		><tbody>
			<tr><td>Issue</td><td>Specification</td><td>1</td><td>80.8</td></tr>
			<tr><td>Issue</td><td>Comment</td><td>6</td><td>64</td></tr>
			<tr><td>Review</td><td>Comment</td><td>7</td><td>83.4</td></tr>
		</tbody></table
	>
	<h6>Conversation Incentives</h6
	><table
		><thead
			><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead
		><tbody
			><tr
				><td
					><h6><a href="https://github.com/ubiquity/.github/issues/95">## Overview We are looking to develop a command-line tool tha...</a></h6></td
				><td
					><details
						><summary>80.8</summary>
						<pre>
h2:
  count: 4
  score: "4"
  words: 5
h3:
  count: 4
  score: "4"
  words: 10
li:
  count: 8
  score: "8"
  words: 127
code:
  count: 1
  score: "1"
  words: 1
</pre
						>
					</details></td
				><td>1</td><td>80.8</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/issues/95#issuecomment-1937025023"
							>> > Include a testing mechanism that prints test results, which ...</a
						></h6
					></td
				><td>4.2</td><td>0.59</td><td>4.2</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/issues/95#issuecomment-1937444788"
							>Use the ts-template repo GitHub actions for inspiration on how t...</a
						></h6
					></td
				><td>14.6</td><td>0.69</td><td>14.6</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/issues/95#issuecomment-1937452787"
							>Keep it extremely simple. Only a subset of permits are stored in...</a
						></h6
					></td
				><td>25.4</td><td>0.73</td><td>25.4</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/issues/95#issuecomment-1937462017"
							>> Is this a hardcoded date btw if so then when? No we should ...</a
						></h6
					></td
				><td>8.4</td><td>0.77</td><td>8.4</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/issues/95#issuecomment-1944488528"
							>Looks like we are exceeding the 65536 character length for GitHu...</a
						></h6
					></td
				><td
					><details
						><summary>8.8</summary>
						<pre>
li:
  count: 1
  score: "1"
  words: 8
</pre
						>
					</details></td
				><td>0.7</td><td>8.8</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/issues/95#issuecomment-1945936317"
							>I'm going to try and salvage the permit link from the logs...</a
						></h6
					></td
				><td>2.6</td><td>0.77</td><td>2.6</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1937489822"
							>I think that parsing the encoded permits from within the GitHub ...</a
						></h6
					></td
				><td>8</td><td>0.695</td><td>8</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1938113569"
							>I appreciate you taking the time to check your work. You can mar...</a
						></h6
					></td
				><td>4.4</td><td>0.77</td><td>4.4</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1941303869"
							>Hey last thing but I'm hoping to see a workflow run can you add ...</a
						></h6
					></td
				><td>8.8</td><td>0.79</td><td>8.8</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1941590512"
							>This doesn't sound right because I've been using `tsx` for proba...</a
						></h6
					></td
				><td
					><details
						><summary>30.6</summary>
						<pre>
code:
  count: 2
  score: "4"
  words: 2
</pre
						>
					</details></td
				><td>0.755</td><td>30.6</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1943245305"
							>I have to see the commit lint error you're talking about because...</a
						></h6
					></td
				><td>22.6</td><td>0.735</td><td>22.6</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1944327565"
							>Can give the full review post merge given the delay and initial ...</a
						></h6
					></td
				><td>2.6</td><td>0.73</td><td>2.6</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1944333152"
							><img width="886" alt="Screenshot 2024-02-15 at 03 01 15" src="ht...</a
						></h6
					></td
				><td>6.4</td><td>0.755</td><td>6.4</td></tr
			></tbody
		></table
	>
</details>

<details>
	<summary>
		<b
			><h3>
				<a
					href="https://pay.ubq.fi/?claim=W3sidHlwZSI6ImVyYzIwLXBlcm1pdCIsInBlcm1pdCI6eyJwZXJtaXR0ZWQiOnsidG9rZW4iOiIweGU5MUQxNTNFMGI0MTUxOEEyQ2U4RGQzRDc5NDRGYTg2MzQ2M2E5N2QiLCJhbW91bnQiOiI0ODY3MDAwMDAwMDAwMDAwMDAwMDAifSwibm9uY2UiOiIxMTE3NDI1MDkxOTM0ODk4Mjg1NjgyMjMxMTA0MTkxODk3MjQyNTA1OTMxOTcwNzEzMjY2MzY5MDU1OTQxMzEzNTg0MTYzNDc5MjQ4ODUiLCJkZWFkbGluZSI6IjExNTc5MjA4OTIzNzMxNjE5NTQyMzU3MDk4NTAwODY4NzkwNzg1MzI2OTk4NDY2NTY0MDU2NDAzOTQ1NzU4NDAwNzkxMzEyOTYzOTkzNSJ9LCJ0cmFuc2ZlckRldGFpbHMiOnsidG8iOiIweEFlNUQxRjE5MjAxM2RiODg5YjFlMjExNUEzNzBhQjEzM2YzNTk3NjUiLCJyZXF1ZXN0ZWRBbW91bnQiOiI0ODY3MDAwMDAwMDAwMDAwMDAwMDAifSwib3duZXIiOiIweDQ0Q2ExNURiMTAxZkQxYzE5NDQ2N0RiNkFGMGM2N0M2QmJGNEFCNTEiLCJzaWduYXR1cmUiOiIweGYwZGNmMDFkN2YxNjg3MzJjMDE3MWJhZDM5NTAyZjRiZDEwYTI0YjA1ZTE3ZDBiNTc1NWI0ODcxNThmNDJjNTMzMDEzYjQ2ZmUwMGRiYjkxODVlMmMyYTUyZWNkMzczYjg1Yzc0NDdiOWI1ZGI0M2I4YTU3ZGQzZDU3ZmUzYjk3MWIiLCJuZXR3b3JrSWQiOjEwMH1d"
				>
					[ 486.7 WXDAI ]</a
				>
			</h3>
			<h6>@Keyrxng</h6></b
		>
	</summary>
	<h6>Contributions Overview</h6>
	<table
		><thead>
			<tr><th>View</th><th>Contribution</th><th>Count</th><th>Reward</th> </tr></thead

		><tbody>
			<tr><td>Issue</td><td>Task</td><td>1.00</td><td>400</td></tr>
			<tr><td>Issue</td><td>Comment</td><td>6</td><td>0</td></tr>
			<tr><td>Review</td><td>Comment</td><td>9</td><td>86.7</td></tr>
		</tbody></table
	>
	<h6>Conversation Incentives</h6
	><table
		><thead
			><tr><th>Comment</th><th>Formatting</th><th>Relevance</th><th>Reward</th></tr></thead
		><tbody
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/issues/95#issuecomment-1937443340"
							>Just seen your comment @pavlovcik, haven't built it with that in...</a
						></h6
					></td
				><td
					><details
						><summary>-</summary>
						<pre>
li:
  count: 5
  score: "0"
  words: 0
</pre
						>
					</details></td
				><td>0.65</td><td>-</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/issues/95#issuecomment-1937447936"
							>I've been able to identify creator/assignee/conversation rewards...</a
						></h6
					></td
				><td
					><details
						><summary>-</summary>
						<pre>
a:
  count: 1
  score: "0"
  words: 2
li:
  count: 3
  score: "0"
  words: 35
</pre
						>
					</details></td
				><td>0.705</td><td>-</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/issues/95#issuecomment-1937454998"
							>![image](https://github.com/ubiquity/.github/assets/106303466/93...</a
						></h6
					></td
				><td
					><details
						><summary>-</summary>
						<pre>
li:
  count: 1
  score: "0"
  words: 11
</pre
						>
					</details></td
				><td>0.78</td><td>-</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/issues/95#issuecomment-1937456134"
							>So I've built this as a CLI tool with multiple commands that par...</a
						></h6
					></td
				><td>-</td><td>0.74</td><td>-</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/issues/95#issuecomment-1937457358"
							>- https://github.com/Keyrxng/ubq-airdrop-cli/actions/runs/786043...</a
						></h6
					></td
				><td
					><details
						><summary>-</summary>
						<pre>
li:
  count: 1
  score: "0"
  words: 10
</pre
						>
					</details></td
				><td>0.685</td><td>-</td></tr
			><tr
				><td
					><h6><a href="https://github.com/ubiquity/.github/issues/95#issuecomment-1937468269">@pavlovcik pr open ...</a></h6></td
				><td>-</td><td>0.76</td><td>-</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1937488661"
							>After you give this a look over let me know if this is the way f...</a
						></h6
					></td
				><td>7.7</td><td>0.65</td><td>7.7</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1937862507"
							>validating the non_payment repos I found one newer style comment...</a
						></h6
					></td
				><td>2.8</td><td>0.665</td><td>2.8</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1938167079"
							>- Now pulling all permits: 448 tracked - Payments assigned to u...</a
						></h6
					></td
				><td
					><details
						><summary>33.7</summary>
						<pre>
a:
  count: 1
  score: "1"
  words: 1
li:
  count: 4
  score: "4"
  words: 0
code:
  count: 2
  score: "2"
  words: 5
</pre
						>
					</details></td
				><td>0.72</td><td>33.7</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1940850278"
							>I don't think I can take this any further without input on it as...</a
						></h6
					></td
				><td>3.9</td><td>0.76</td><td>3.9</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1941559807"
							>Is tsx a requirement if it's running fine with tsc? I can run th...</a
						></h6
					></td
				><td
					><details
						><summary>8.8</summary>
						<pre>
a:
  count: 1
  score: "1"
  words: 3
</pre
						>
					</details></td
				><td>0.725</td><td>8.8</td></tr
			><tr
				><td
					><h6
						><a href="https://github.com/ubiquity/.github/pull/96#issuecomment-1941611149"
							>I'll see what I can do with it then pav and I'll make the final ...</a
						></h6
					></td
				><td>3.3</td><td>0.805</td><td>3.3</td></tr
			><tr
				><td><h6></h6> </td>
			</tr>
		</tbody> </table
></details>

**Comment by Keyrxng** [comment]
> I'm going to try and salvage the permit link from the logs

I beat you to it this morning when I realised it was sitting in the logs (had I not been skint rn I'd have left it)

Was gonna jump in and try resolve the issue myself until I realised it's AI heavy and I had an API bill to pay 🤣 however with that said, I'll likely attempt it later

**Comment by Keyrxng** [comment]
82 bucks for conversation that's mad

**Comment by pavlovcik** [comment]
> 86 bucks for conversation that's mad

In the future we will augment the bot's capabilities to determine if the subject is accurate (for example, on the issues page, the conversation should only be around refining the scope of work with clarifications etc. 

In the pull request review, the conversation should focus on improving the code quality. Although I think in a more advanced stage, we would very likely remove the assignee rewards for commenting on the review. However I think the assignee should be eligible for rewards to contribute to researching the original issue specification before they take on the task. 

Lastly I do full expect to increase the rewards by 2-4x as we move the core team off of salaries. In this way, the bot should be finely tuned to incentivize the precise behavior we seek, and developers should make good living wages if they pursue these incentives.

**Comment by Keyrxng** [comment]
I agree hashing out the spec should surely count but pr comments nah, you've accepted the terms as soon as the /start command is ran if you ask me 😂 esp considering those PRs that extend months and amount to double digit review attempts, too easily gamed.

Well if I never end up making the cut before then I'll still be glad to be around when that does happen. My annual hiatus is over so I'll be pushing often again wherever I can be of value
